type Copy = readonly [en: string, sv: string];
export type Guide = {
  slug: string; title: Copy; description: Copy; intro: Copy; destination: string; cta: Copy;
  sections: { title: Copy; body: Copy }[];
  questions: { question: Copy; answer: Copy }[];
};

export const guides: Guide[] = [
  {
    slug: "qr-moving-box-labels",
    title: ["How to label moving boxes with QR codes", "Så märker du flyttkartonger med QR-koder"],
    description: ["Create printable moving box labels, list the contents and scan to find your things. A practical packing guide with eight free QR labels in StayTag Move.", "Skapa etiketter för flyttkartonger, lista innehållet och skanna för att hitta dina saker. En praktisk packguide med åtta gratis QR-etiketter i StayTag Move."],
    intro: ["A box marked Kitchen tells a helper where to put it. A numbered QR label also tells you whether the kettle, mugs or coffee maker are inside. Use one box number everywhere: on the label, in the packing list and when asking someone to find it.", "Kök på en kartong talar om var den ska ställas. En numrerad QR-etikett visar också om vattenkokaren, muggarna eller kaffemaskinen ligger i den. Använd samma kartongnummer på etiketten, i packlistan och när någon ska hitta den."],
    destination: "/move", cta: ["Create free moving box labels", "Skapa gratis flyttetiketter"],
    sections: [
      { title: ["1. Give each box a number and a destination room", "1. Ge kartongen ett nummer och ett rum"], body: ["Open StayTag Move, name your move and choose the room at the new home. Each new box gets the next number. Keep room names consistent so helpers can sort boxes without opening them. The printed colour band supports the written room name; the number still works on a black-and-white printer.", "Öppna StayTag Move, namnge flytten och välj rum i det nya hemmet. Nästa kartong får nästa nummer. Använd samma rumsnamn så att hjälpare kan sortera utan att öppna. Färgbandet kompletterar rumsnamnet; numret fungerar även med svartvit utskrift." ] },
      { title: ["2. List items you will search for", "2. Lista saker som du kommer att leta efter"], body: ["Write Kettle, Coffee maker and Mugs rather than Miscellaneous. Paste one item per line or separate them with commas. Add fragile or heavy flags and a short handling note. Each box holds up to 40 item names. Leave addresses, door codes, personal documents and descriptions of valuables out of the QR: anyone who sees the label can scan it.", "Skriv Vattenkokare, Kaffemaskin och Muggar i stället för Diverse. Klistra in en sak per rad eller separera med kommatecken. Markera ömtåligt eller tungt och lägg till en kort hanteringsnotering. En kartong rymmer upp till 40 benämningar. Skriv inte adresser, portkoder, privata dokument eller värdesaker: alla som ser etiketten kan skanna den." ] },
      { title: ["3. Print, scan-test and attach the label", "3. Skriv ut, provskanna och fäst etiketten"], body: ["Print the labels on plain A4 paper, two labels per page. Test one with your phone camera before printing the whole move. Keep the QR flat and clear; avoid creases, glare and tape across the code. Place a copy on the top and another on the side if boxes will be stacked. Keep the room and box number visible even when scanning is inconvenient.", "Skriv ut på vanligt A4-papper, två etiketter per sida. Testa en med mobilkameran innan du skriver ut hela flytten. Håll QR-koden plan och tydlig utan veck, reflexer eller tejp över koden. Fäst en kopia ovanpå och en på sidan om kartongerna ska staplas. Låt rummet och numret vara synliga även när skanning är opraktisk." ] },
      { title: ["4. Find the right box while unpacking", "4. Hitta rätt kartong när du packar upp"], body: ["Scan a box to read its contents in a browser. On the device used for packing, search the full move for kettle or charger and get the box number. Mark a box unpacked when it is empty. Print the box index as a paper fallback. The full move stays in that browser: changing phones or clearing browser storage will not transfer it automatically.", "Skanna en kartong för att läsa innehållet i webbläsaren. Sök efter vattenkokare eller laddare på enheten där du packade och få kartongnumret. Markera kartongen som uppackad när den är tom. Skriv ut kartonglistan som reserv. Hela flytten ligger i den webbläsaren och överförs inte automatiskt vid mobilbyte eller rensad lagring." ] },
      { title: ["What is free, and what does Move Pass add?", "Vad är gratis och vad ger Move Pass?"], body: ["Create and print three boxes free. Move Pass costs SEK 79 once and lifts that free-box limit, up to the planner's 300-box capacity. Euro amounts are estimates; Stripe shows the checkout total. You do not need an account, a label printer or a paid mobile app. An existing printed label is a snapshot: if contents change, print a new QR and cover the old one.", "Skapa och skriv ut tre kartonger gratis. Move Pass kostar 79 kr en gång och tar bort gratisgränsen, upp till planerarens kapacitet på 300 kartonger. Eurobelopp är uppskattningar; Stripe visar kassans belopp. Du behöver inget konto, ingen etikettskrivare och ingen betald mobilapp. En utskriven etikett är en ögonblicksbild: ändras innehållet behöver du skriva ut en ny QR och täcka den gamla." ] }
    ],
    questions: [
      { question: ["Does the person scanning need the app?", "Behöver den som skannar en app?"], answer: ["No StayTag app or account is needed. A phone camera or QR reader opens the contents page in a browser. Loading the page needs an internet connection.", "Ingen StayTag-app eller konto behövs. Mobilkameran eller en QR-läsare öppnar innehållssidan i webbläsaren. Internet behövs för att ladda sidan." ] },
      { question: ["Can I use the full packing list on another phone?", "Kan jag använda hela packlistan på en annan mobil?"], answer: ["Box QRs are readable on another phone, but the full searchable move is saved locally on the packing device. Keep a printed index; there is no cloud sync.", "Kartongernas QR-koder går att läsa på en annan mobil, men hela den sökbara flytten sparas på packningsenheten. Behåll en utskriven lista; molnsynkning finns inte." ] }
    ]
  },
  {
    slug: "qr-maintenance-labels",
    title: ["How to make a QR maintenance label", "Så gör du en QR-etikett för underhåll"],
    description: ["Keep exact filter part numbers, replacement dates and care history on a printable QR maintenance label. Free labels for household machines and office equipment.", "Spara rätt filterartikelnummer, bytesdatum och skötselhistorik på en utskrivbar QR-etikett. Gratis etiketter för hushållsmaskiner och kontorsutrustning."],
    intro: ["A maintenance label answers three practical questions: which part fits, when was it last replaced, and when is the next change due? Put that record on the machine instead of depending on packaging that will be thrown away. StayTag generates the label in your browser without an account or a tag database.", "En underhållsetikett besvarar tre frågor: vilken del passar, när byttes den senast och när är nästa byte? Fäst posten på maskinen i stället för att förlita dig på förpackningar som slängs. StayTag skapar etiketten i webbläsaren utan konto eller etikettdatabas."],
    destination: "/#create", cta: ["Create a free maintenance label", "Skapa en gratis underhållsetikett"],
    sections: [
      { title: ["1. Record the exact item and part number", "1. Ange rätt benämning och artikelnummer"], body: ["Use a specific name such as Coffee machine water filter. Copy the part number from the installed filter, its packaging or the manufacturer's manual. A machine model and a replacement part number are not always the same thing. Check compatibility before ordering; an optional marketplace search helps you find listings but does not certify that a part fits.", "Använd en tydlig benämning som Vattenfilter till kaffemaskin. Kopiera artikelnumret från filtret, förpackningen eller tillverkarens manual. Maskinens modell och reservdelens artikelnummer är inte alltid samma sak. Kontrollera kompatibiliteten före köp; en valfri butikssökning hittar annonser men intygar inte att delen passar." ] },
      { title: ["2. Add the replacement date and interval", "2. Ange bytesdatum och intervall"], body: ["Enter the date you actually changed the part. Choose an interval in days using the manufacturer's instructions and your own operating conditions. StayTag calculates the next date from that entry; its suggested intervals are starting points, not manufacturer-approved schedules. For a task without a known history, do not invent a previous service date.", "Ange datumet då du faktiskt bytte delen. Välj ett intervall i dagar enligt tillverkarens instruktioner och användningen. StayTag räknar fram nästa datum; föreslagna intervall är startvärden och inte tillverkargodkända scheman. Hitta inte på ett tidigare servicedatum om historiken är okänd." ] },
      { title: ["3. Preview the public information before printing", "3. Granska de offentliga uppgifterna före utskrift"], body: ["The QR carries the item, part details and care dates in its link. Anyone with the sticker or link can read those fields. Leave out names, addresses, passwords and confidential asset details. An optional photo hash is calculated on your device: the original image is not uploaded. A hash identifies a file; it does not independently prove that maintenance happened.", "QR-länken innehåller benämning, deluppgifter och skötseldatum. Alla med etiketten eller länken kan läsa dem. Utelämna namn, adresser, lösenord och konfidentiella tillgångsuppgifter. En valfri bildhash beräknas på enheten utan bilduppladdning. Hashen identifierar en fil men bevisar inte oberoende att underhållet utförts." ] },
      { title: ["4. Attach a readable label near the part", "4. Fäst en läsbar etikett nära delen"], body: ["Print one label or download its PNG. For several machines, use free Bulk or the free 12-up Care Sheet. Test a label with your phone camera and place it where it stays clean and dry, away from heat and moving parts. Keep good contrast and the blank border around the QR. The camera opens a browser page; no StayTag app is required.", "Skriv ut en etikett eller ladda ner PNG-bilden. För flera maskiner finns gratis Bulk och Care Sheet med tolv etiketter per ark. Provskanna med mobilkameran och placera etiketten rent och torrt, bort från värme och rörliga delar. Behåll kontrasten och den tomma kanten runt QR-koden. Kameran öppnar en webbsida; ingen StayTag-app behövs." ] },
      { title: ["5. Log the next replacement and reprint", "5. Logga nästa byte och skriv ut igen"], body: ["When you replace the part, scan and choose I replaced it today. The app issues a new QR carrying the updated dates and available care history. Print it and cover the old sticker. Old QRs remain fixed snapshots and do not update remotely. My tags can keep a local copy for reprinting; keep your own exported link or printout because browser storage is not a cloud backup.", "När du byter delen, skanna och välj Jag bytte den i dag. Appen skapar en ny QR med uppdaterade datum och tillgänglig historik. Skriv ut och täck den gamla etiketten. Gamla QR-koder är fasta ögonblicksbilder och uppdateras inte på distans. Mina etiketter kan spara en lokal kopia; behåll egen länk eller utskrift eftersom webbläsarlagring inte är molnbackup." ] }
    ],
    questions: [
      { question: ["Does StayTag verify the maintenance record?", "Verifierar StayTag underhållet?"], answer: ["No. Dates and descriptions are entered by the owner. This is a useful care record, not a certified inspection report, warranty certificate or independent proof of service.", "Nej. Ägaren anger datum och beskrivningar. Det är en skötselpost, inte ett certifierat besiktningsprotokoll, garantibevis eller oberoende servicebevis." ] },
      { question: ["Are labels and printable sheets free?", "Är etiketter och utskrivbara ark gratis?"], answer: ["Yes. Individual maintenance labels, Bulk and Care Sheet are free. Optional marketplace links may earn an affiliate commission, and voluntary support purchases no extra maintenance features.", "Ja. Enskilda underhållsetiketter, Bulk och Care Sheet är gratis. Valfria butikslänkar kan ge affiliateprovision och frivilligt stöd köper inga extra underhållsfunktioner." ] }
    ]
  }
];

export const guideUpdated = "2026-10-02";
export function guidePath(guide: Guide) { return `/guides/${guide.slug}`; }
export function getGuide(slug: string) { return guides.find(guide => guide.slug === slug); }
