type Copy = readonly [en: string, sv: string];
export const moveFaq: { q: Copy; a: Copy }[] = [
  { q: ["Do my helpers need an app to scan the boxes?", "Behöver hjälparna en app för att skanna?"], a: ["No. Any phone camera opens the box contents in a normal web page. No app or account.", "Nej. Vilken mobilkamera som helst öppnar innehållet i en vanlig webbsida. Ingen app, inget konto."] },
  { q: ["Is it free?", "Är det gratis?"], a: ["The first 3 boxes are free, including printing and scanning. A Move Pass for unlimited boxes is SEK 79 once.", "De första 3 kartongerna är gratis, med utskrift och skanning. Ett Move Pass för obegränsat antal kartonger kostar 79 kr en gång."] },
  { q: ["Do I need a label printer?", "Behöver jag en etikettskrivare?"], a: ["No. Labels print on plain A4 or US Letter paper, two per sheet. Tape them on with packing tape.", "Nej. Etiketterna skrivs ut på vanligt A4-papper, två per ark. Fäst dem med packtejp."] },
  { q: ["Where is my box list stored?", "Var sparas min kartonglista?"], a: ["In your browser on the device you packed with. Each QR holds only that box's contents. We never receive your list.", "I webbläsaren på enheten du packade med. Varje QR innehåller bara den kartongens innehåll. Vi tar aldrig emot din lista."] },
  { q: ["Can I search for an item across all boxes?", "Kan jag söka efter en sak i alla kartonger?"], a: ["Yes, on the device you packed with: search a word like charger and get the box number and room. Print the box index as a paper backup.", "Ja, på enheten du packade med: sök ett ord som laddare och få kartongnummer och rum. Skriv ut kartonglistan som pappersreserv."] },
  { q: ["What if I repack a box?", "Vad gör jag om jag packar om en kartong?"], a: ["Edit the box and print a new label to tape over the old one. A printed QR is a snapshot of the contents when you printed it.", "Ändra kartongen och skriv ut en ny etikett att tejpa över den gamla. En utskriven QR är en ögonblicksbild av innehållet vid utskrift."] },
];
