import type { Metadata } from "next";
import { contact, contactLinks, operatorTaxDisclosure, operatorLegalLine } from "@/lib/contact";

export const metadata: Metadata = { title: "Privacy", alternates: { canonical: "/privacy" }, openGraph: { url: "/privacy" } };

export default function PrivacyPage() {
  return <Legal title="Privacy policy" updated="25 September 2026">
    <h2>Operator</h2>
    <p>{operatorLegalLine}</p>
    <p>{contact.productName} is a product of <a href={contactLinks.operator}>{contact.operatorName}</a> in {contact.country}. {contact.operatorName} is a {contact.legalForm}. {operatorTaxDisclosure}</p>
    <h2>What StayTag stores</h2><p>StayTag does not provide accounts and does not store the content of tags in a database. Item names, optional part numbers, replacement dates, intervals, care history, optional photo hashes and marketplace settings are encoded after the # in the URL and QR code. Browsers do not send that fragment to the web server. Anyone with the QR or link can read these fields.</p>
    <h2>Optional photos</h2><p>Photo hashing runs locally in your browser using SHA-256. StayTag never uploads or stores the photo. Only its hash is included in the tag and optional local My tags shelf. Keep the original file yourself; a hash cannot reconstruct the photo or certify maintenance.</p>
    <h2>On-device list</h2><p>If your browser allows it, StayTag can keep a short list of tags you create so you can reopen or print them later. That list stays in the browser and is not uploaded. Private mode, blocked site data or a full storage quota can prevent saving; the QR and share link still work. Clearing the list, clearing site data or switching browsers removes the local copy. Printed labels are unchanged.</p>
    <h2>Hosting logs</h2><p>The hosting provider may process ordinary request metadata such as IP address, user agent, requested path and timestamp for security and service operation. Newly generated tag data is kept in the URL fragment rather than the requested path. StayTag does not add advertising pixels or tracking cookies.</p>
    <h2>Minimal action counts</h2><p>On production we send only an allowed event name and a fixed page category for page views, starting and creating labels, print-dialog requests, PNG downloads, store-link clicks and opening voluntary support checkout. We do not include URLs, QR contents, item names, search phrases, photo hashes, referrers, account IDs or visitor identifiers in these events. Hosting infrastructure may still process ordinary request metadata as described above. These are action counts, not unique visitors or linked individual journeys. Do Not Track and Global Privacy Control disable this measurement. Preview deployments and QA tabs are excluded. No payment is inferred from a click; payment status is checked in Stripe.</p><p>Your language choice is saved locally. Country headers are used transiently to suggest an eBay marketplace; country is not included in action events. The selected region can be changed before printing.</p>
    <h2>Refill Relay</h2><p>Your refill list contains item names, search phrases, marketplaces and quantities. It is saved only in this browser when storage is available; if saving fails, the interface warns you to keep a share link before leaving. Shared lists encode those fields after the # in a link, without a StayTag database. Anyone receiving or forwarding that link can read them. Sharing through another app is your choice and that app processes the information under its own policy. Received lists are snapshots and do not overwrite your saved list. “Got it” checkmarks stay in the current tab and reset on reload; no purchase or delivery confirmation is sent. Remove local items in Refill Relay or clear this site’s browser data. Deleting your copy does not revoke copies already shared.</p>
    <h2>Marketplace links</h2><p>When you choose a marketplace link, that marketplace applies its own privacy policy. StayTag currently routes each shopping region to one eBay marketplace (for example Europe / Nordics opens eBay.de). Links may contain an affiliate campaign identifier and a non-personal category label.</p>
    <h2>Your control</h2><p>Anyone with a tag link can read the information encoded in it. The create flow previews the item name, search, date, market and share link before the QR is generated. Do not put personal, confidential or sensitive information in a tag. Destroy the printed tag and delete its link to remove your copy. The optional My tags list can be removed one item at a time or cleared on this device; StayTag has no server copy of it. Correcting a typo creates a new QR; previously printed labels continue to open the original details because StayTag cannot rewrite a sticker.</p>
    <h2>Privacy and GDPR requests</h2><p>For privacy questions, access requests or deletion requests, email <a href={contactLinks.privacy}>{contact.email.privacy}</a>.</p>
    <h2>Seller Kits</h2><p>Seller Kits encode the creator-supplied seller name, product, SKU, language and store URLs in the QR link fragment. They are public to anyone with the link and are not verified seller profiles. StayTag does not fetch these destinations. A store click can contribute an action count without recording the destination. Clicking a store link opens that store under its own privacy policy; URLs may contain creator-supplied affiliate or campaign parameters. StayTag does not add or replace affiliate IDs in Seller Kit links. Cards are fixed snapshots and cannot be revoked centrally. The pilot enquiry button opens your email app; it sends nothing until you choose to send.</p>
  </Legal>;
}

function Legal({ title, updated, children }: { title: string; updated: string; children: React.ReactNode }) {
  return <main className="legal-page"><article><div className="section-kicker">STAYTAG</div><h1>{title}</h1><p className="updated">Last updated {updated}</p>{children}</article></main>;
}

