import type { Metadata } from "next";
export const metadata: Metadata = { title: "Mätning och beslut", robots: { index: false, follow: false } };
export default function Insights() {
  return <main className="legal-page" lang="sv"><article>
    <div className="section-kicker">STAYTAG / ÄGARGUIDE</div><h1>Vad händer efter klicket?</h1>
    <p>Ingen publik statistik visas här. Siffrorna finns i dina egna Vercel-, eBay- och Stripe-konton. Mätningen börjar med denna version; gamla besök går inte att återskapa.</p>
    <h2>0. Hittar folk sidan? Google Search Console</h2>
    <p>Öppna <a href="https://search.google.com/search-console" rel="noopener noreferrer" target="_blank">Google Search Console</a>. Verifiera domänegendomen <code>nyttolabs.com</code> med Googles DNS-post, eller URL-prefixet <code>https://staytag.nyttolabs.com/</code> med den verifieringsmetod Google visar. Domänverifiering ska göras där domänens DNS faktiskt hanteras.</p>
    <p>Skicka <code>https://staytag.nyttolabs.com/sitemap.xml</code> under Sitemaps. Inspektera startsidan, <code>/move</code> och de två <code>/guides/</code>-sidorna och begär indexering. Innehåll i privata QR-länkar ska inte skickas in. Gamla <code>cycletag.eu</code> måste fortsätta fungera. Kontrollera Googles adressändringsverktyg för den verifierade gamla egendomen om flytten inte redan anmälts.</p>
    <p>Under Performance → Search results: filtrera på <code>https://staytag.nyttolabs.com/</code> och jämför sökfrågor, visningar och klick över 28 dagar. Visningar utan klick pekar mot sökfråga, position eller presentation. Inga visningar kräver först kontroll av indexering och faktisk sökefterfrågan. Ett sökkommando som <code>site:</code> är inte en fullständig indexrapport.</p>
    <p>Search Console är inte kopplat till denna app. Denna guide visar hur du läser riktiga siffror; den påstår inte att Google redan indexerat sidorna. IndexNow meddelar deltagande sökmotorer och ersätter inte Google Search Console.</p>
    <h2>1. Besök och handlingar: Vercel</h2>
    <p>Öppna projektet <strong>cycletag → Logs</strong>. Välj Production, önskat tidsintervall och sök <code>staytag_event</code>. Filtrera på <code>/api/metrics</code>. Räkna loggmeddelanden med respektive event nedan, inte alla HTTP-anrop.</p>
    <ul><li><code>page_view</code> + <code>source: home</code>: startsidan visades med JavaScript.</li><li><code>label_started</code>: någon började använda formuläret.</li><li><code>label_created</code>: en QR skapades; bulk räknas som en omgång.</li><li><code>print_requested</code>: utskriftsdialogen öppnades, inte bevis på utskrivet papper.</li><li><code>png_downloaded</code>: nedladdning begärdes.</li><li><code>outbound_ebay</code>: en eBay-länk aktiverades.</li><li><code>support_checkout_opened</code>: stödkassan öppnades, inte en betalning.</li><li><code>tag_scanned</code>: en etikett öppnades på skanningssidan (inkluderar egna öppningar).</li><li><code>replacement_logged</code>: ”Jag bytte den” skapade en ny etikett.</li><li><code>refill_added</code> / <code>relay_shared</code>: något lades i inköpslistan / listan delades.</li><li><code>space_created</code>: en Space-QR skapades.</li><li><code>return_wallet_opened</code>, <code>return_added</code>, <code>return_code_opened</code>, <code>return_dropped_off</code>, <code>return_refunded</code>, <code>return_reminder_added</code>: Returplånbokens flöde. Återkommande användning syns som <code>return_code_opened</code> och <code>return_dropped_off</code>.</li></ul>
    <p>Detta är handlingar, inte unika människor eller sammanlänkade personresor. Omladdningar kan ge fler besök; integritetsskydd och nätfel kan ge bortfall. Do Not Track och Global Privacy Control respekteras. Öppna sidan med <code>?qa=1</code> för egna tester: den fliken räknas därefter inte.</p>
    <p><strong>Spara resultaten innan loggarna försvinner.</strong> Vercels lagringstid beror på abonnemanget; kontrollera den i ditt konto. Kort logglagring ger ingen komplett sjudagarsrapport. Exportera inom lagringstiden eller konfigurera beständig lagring av enbart dessa fasta event innan ett längre test. Ingen sådan betaltjänst aktiveras automatiskt.</p>
    <h2>2. Registrerade affiliateklick: eBay</h2>
    <p>I eBay Partner Network: välj kampanj <strong>5339198614</strong>, samma datum och tidszon. Jämför registrerade klick med <code>outbound_ebay</code>. Custom ID börjar med <code>cycletag-scan-</code>, <code>cycletag-instant-</code> eller <code>cycletag-printer-</code>; äldre prefix bevaras avsiktligt. Kontrollera även andra verktygs prefix om de används.</p>
    <p>En korrekt märkt länk och ett butiksklick bevisar inte att EPN registrerat klicket eller att någon köpt. EPN:s rapportering och kvalificeringsregler avgör provision. Startsidesbesök utan butiksklick ska inte synas som EPN-klick.</p>
    <h2>3. Riktiga betalningar: Stripe</h2>
    <p>Öppna Payment Links → <strong>Support CycleTag</strong> (det tidigare namnet). Kontrollera lyckade betalningar för just denna länk under testperioden. Länken tar frivilligt stöd från 49 SEK och levererar ingen betalprodukt. En startad eller slutförd kassa med obetald status räknas inte som intäkt. Kontrollera också återbetalningar.</p>
    <p><strong>Move Pass är separat:</strong> välj Payment Link för <strong>StayTag Move Pass</strong> och kontrollera lyckade betalningar, SEK 79 per engångsköp. I Vercel visar <code>move_box_added</code>, <code>move_paywall_shown</code> och <code>move_checkout_opened</code> användning före köp. <code>move_pass_unlocked</code> visar aktivering eller återställning på en enhet och kan ske flera gånger för samma betalning. Räkna därför intäkter i Stripe, aldrig från dessa event.</p>
    <h2>Beslut efter ett avgränsat test</h2>
    <p>Testa i sju dagar med en tydlig målgrupp: personer som faktiskt sköter flera maskiner. Bestäm i förväg hur besök ska räknas över hela perioden. Utan tillräcklig relevant trafik går betalviljan inte att bedöma.</p>
    <p>Få besök: arbeta med distribution. Besök men få påbörjade etiketter: erbjudandet eller målgruppen brister. Många starter men få skapade: undersök formulärfel. Skapade etiketter utan butiksklick: det kan vara normal användning av skötselhistorik. Butiksklick utan EPN-klick: granska attribution. Ingen verifierad betalvilja efter testet: pausa vidare utveckling och behåll gratisverktyget.</p>
    <p><strong>Det konkreta betalerbjudandet är Move Pass:</strong> fler än åtta kartonger i flyttplaneraren, med dess kapacitetsgräns på 300 kartonger. Testa det separat på personer som faktiskt ska flytta. Underhållsetiketter, Care Sheet och Bulk är gratis; sälj inte dessa som ett betalpaket. Klick och skapade etiketter är inte bevis på försäljning.</p>
  </article></main>;
}
